feat(PDO-108):implement url routers
dulinajayarathna/student_resgistration_app pull request #7
Opened 2024-08-04 11:18 UTC by dulinajayarathna

2024-08-04 11:21 UTC, HarshaAbeyvickrama requested changes

2024-08-04 11:21 UTC, HarshaAbeyvickrama commented on student/views.py
> +class StudentViewSet(viewsets.ModelViewSet):
Add a comment to StudentViewSet

2024-08-11 12:49 UTC, HarshaAbeyvickrama requested changes

2024-08-11 12:49 UTC, HarshaAbeyvickrama commented on README.md
> +    cd <student_resgistration_app-directory>
@dulinajayarathna correct the directory name

2024-08-11 12:52 UTC, dulinajayarathna commented on README.md
> +    cd <student_resgistration_app-directory>
Resolved

2024-08-11 12:53 UTC, HarshaAbeyvickrama approved these changes

2024-08-11 12:53 UTC, merged